class ConftestNotFoundError(Exception):
    pass


class ConftestRunError(Exception):
    pass
